# Generated by Django 3.2.3 on 2021-05-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='viewsAmount',
            field=models.IntegerField(default=0),
        ),
    ]
